version: '3.3'
services:
    adguard:
        container_name: adguard
        restart: always
        volumes:
            - '/var/lib/adguard/work:/opt/adguardhome/work'
            - '/var/lib/adguard/conf:/opt/adguardhome/conf'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
            - '3000:3000/tcp'
        image: adguard/adguardhome
